apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-model-deploy
  labels:
    app: ai-model-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-model-deploy
  template:
    metadata:
      labels:
        app: ai-model-deploy
    spec:
      containers:
        - name: ai-model-deploy
          image: ai-model-deploy:latest
          imagePullPolicy: IfNotPresent   # local image (Minikube/Kind) ke liye
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20
